// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Centralised British-English UI strings for admin-client. Pages add their
 * own keys as they are built; do not inline literal strings anywhere except
 * here.
 */
export const copy = {
  appName: 'Chatsundere Admin',
  signOut: 'Sign out',
  loading: 'Loading…',
  genericError: 'Something went wrong. Please try again.',
  login: {
    title: 'Sign in to Chatsundere Admin',
    passphraseLabel: 'Passphrase',
    submit: 'Sign in',
    failures: {
      noAccount: {
        title: 'No account on this device',
        body: 'Set up a Chatsundere account in user-client first, then come back here.',
        cta: 'Open user-client',
      },
      noLink: {
        title: 'Account is not linked to a server',
        body: 'Admin features require a server connection. Link your account in user-client first.',
        cta: 'Open user-client',
      },
      offline: {
        title: 'Server connection required',
        body: 'Admin-client requires an active server connection. Check your network and try again.',
        cta: 'Retry',
      },
      notAdmin: {
        title: 'Admin permissions required',
        body: 'Your account does not have admin permissions on this server. If you believe this is wrong, contact your operator.',
        cta: 'Open user-client',
      },
    },
    errors: {
      invalidPassphrase: 'Incorrect passphrase.',
      integrityFailure: "Couldn't verify your local data. Try clearing site data and re-linking.",
      authFailed: 'Authentication failed.',
      serverUnreachable: 'Could not reach the server.',
      genericError: 'Something went wrong. Please try again.',
      prfRequired: 'Your passkey does not support PRF — needed for biometric login.',
      passkeyCancelled: '',
    },
  } as const,
  dashboard: {
    title: 'Dashboard',
    cards: {
      totalUsers: 'Total users',
      pendingInvitations: 'Pending invitations',
      suspendedUsers: 'Suspended users',
    },
    recentActivity: 'Recent activity',
    noActivity: 'No recent activity.',
    viewUsers: 'View users',
  },
  users: {
    title: 'Users',
    searchPlaceholder: 'Search by username',
    roleFilter: {
      all: 'All roles',
      primary_admin: 'Primary admin',
      admin: 'Admin',
      user: 'User',
    },
    statusFilter: { all: 'All statuses', active: 'Active', suspended: 'Suspended' },
    columns: {
      username: 'Username',
      role: 'Role',
      status: 'Status',
      createdAt: 'Created',
      lastLogin: 'Last login',
    },
    createInvitation: 'Create invitation',
    empty: 'Just you so far. Create an invitation to add the next user.',
    pagePrev: '← Previous',
    pageNext: 'Next →',
  },
  userDetail: {
    backLink: '← Back to all users',
    role: 'Role',
    status: 'Status',
    createdAt: 'Created',
    lastLogin: 'Last login',
    authMethods: 'Authentication methods',
    actions: {
      suspend: 'Suspend',
      unsuspend: 'Unsuspend',
      changeRole: 'Change role',
      transferPrimary: 'Transfer primary admin',
      delete: 'Delete user',
    },
    changeRoleNotYetAvailable: 'Coming in a later release.',
    selfTargetTooltip: 'You cannot perform this action on your own account.',
    primaryOnlyTooltip: 'Only the primary admin can perform this action.',
    transferOnlyAdminTooltip: 'Can only transfer to a user with the admin role.',
    lastPrimaryAdminTooltip:
      'This is the only primary admin. Transfer the role to another admin first.',
    deleteConfirm: {
      title: 'Delete this user?',
      body: 'This action is irreversible. The user loses access immediately and their server-side record is removed. To confirm, type the username below exactly.',
      tokenLabel: 'username',
      destructiveCta: 'Delete user',
      cancelCta: 'Cancel',
    },
  },
  invitations: {
    title: 'Invitations',
    create: 'Create invitation',
    revoke: 'Revoke',
    filter: {
      all: 'All',
      pending: 'Pending',
      redeemed: 'Redeemed',
      expired: 'Expired',
      revoked: 'Revoked',
    },
    columns: {
      createdAt: 'Created',
      role: 'Role',
      status: 'Status',
      redeemedBy: 'Redeemed by',
      expiresAt: 'Expires',
      issuerLabel: 'Label',
      note: 'Note',
      noteHover: 'Note ↗',
    },
    empty: 'No invitations yet. Create one to start onboarding people.',
    modal: {
      title: 'Create invitation',
      role: 'Role',
      roleOptions: { user: 'User', admin: 'Admin' },
      expiresIn: 'Expires in',
      expiresOptions: { day: '1 day', week: '7 days', month: '30 days' },
      issuerLabel: 'Issuer label (optional)',
      issuerLabelHint: "Categorical label visible only to admins (e.g. 'June 2026 wave').",
      suggestedUsername: 'Suggested username (optional)',
      note: 'Note (optional)',
      noteHint:
        'Freeform note about this invitation. Operator-private — the redeeming user never sees it.',
      submit: 'Create',
      cancel: 'Cancel',
    },
    reveal: {
      title: 'Invitation created',
      warning: 'This is shown only once. Make sure to capture it before closing.',
      urlLabel: 'URL',
      copyUrl: 'Copy URL',
      close: 'Close',
    },
  },
  nav: {
    dashboard: 'Dashboard',
    users: 'Users',
    invitations: 'Invitations',
    audit: 'Audit',
  },
  audit: {
    title: 'Audit log',
    filters: {
      category: 'Category',
      user: 'User ID',
      from: 'From',
      to: 'To',
    },
    categories: {
      all: 'All categories',
      auth: 'Auth',
      'user-lifecycle': 'User lifecycle',
      'invitation-lifecycle': 'Invitation lifecycle',
      recovery: 'Recovery',
      'admin-action': 'Admin action',
    },
    columns: {
      timestamp: 'Timestamp',
      eventType: 'Event',
      actor: 'Actor',
      subject: 'Subject',
      metadata: 'Metadata',
    },
    expand: 'Expand',
    collapse: 'Collapse',
    empty: 'No matching events. Try a wider time range.',
  },
} as const;
